### ISSUE TITLE
FIlenaming

### ISSUE THREAD

**Issue by eah13** [silshack/spring2016#485]
@wagerpascal A few of your posts use `_` instead of `-` in the names.  Take a look and fix this when you're able.

**Comment by wagerpascal** [comment]
Should be fixed now.

**Comment by eah13** [comment]
@wagerpascal I still see a few that are still unchanged.  There are some with spaces in the title too

https://github.com/silshack/spring2016/tree/gh-pages/_posts/jasonwang

Also I didn't see pull requests for these.  You shouldn't be committing directly to gh-pages, even for small changes like this.  Should be only 1-2 clicks more than committing directly.

**Comment by wagerpascal** [comment]
@eah13 That's completely my bad. I have cleaned out the duplicate pages I believe, and I corrected the post with the space in the title.

**Comment by eah13** [comment]
No prob! That directory looks spic and span now. :star:
